language: node_js
script:
- make test
env:
  global:
    secure: Kn1eyLzmQdRZfb6gOsqte3px+4H2khxNhtuO5zXwpcQwaTYBUiiYS8zgX+LPCG54tdAG64fmSUtCPI6pZAVuj461+n537MfGADC3WUdgwexIiv4XXmJXiRrnRkTJyFbYRx5FZ0GULcLrT8WlX4viEx/aYcQTYHNrbcn2BfoPkg74QujTrLkXznsK6EmSAXQpc73utfEw1O3jlr8sJOBFPhWBHaQxvKoaNBwx1bYzuUcmx70HnedXyUyEg1MpqjiQT5Q4eqhr8WQtDGgEfj1+JDPel78FXv0W1OIYr08XiNZIr8ICbUZwj91GBjYei+wS20UtBHy5Zm1z8vplEhpW7TB5mj+96josWw7Q5OTXtVBCRyvdXMphMYfa/q8OmToxHA2jUa32te+Bm2AxTrS9w+MG02vHbJW9ovVVS+z1M14cTpPkT3VlWzWFkldkr3u+sw1AGHgXifacFlXtz48C0sKiTS4yPn9Dne6qeehrrKIwplKhmm9i2UayoxlVEyFJPnuLOud7QiCGAy7nWQCsI9a9GuMpHhGiJVMi3p/m2rHSFai4RQGQsolp+4iz7wr4WwrVB/YzCyruUsl0PenMdtCJuP9PWEJCXjz1iF8to8cR5RX2BjETpTVRx9GlCQvx7AIqEJ16SthZY7+nRw2fqqSUbXHpKlylZ7s7GLwgMO0=
