language: node_js
script:
 - make test
env:
  global:
    TRAVIS_KEYS_PASSPHRASE:
      secure: yTjPLXxlJ6zIDZGF8T59ZX+eU5h6/xz9rsoVPs1Y0My+2NUnoySuzqBHwIxw3lnlY4/9nsjw6PqIyCIKRoAkBAHFnVH7Qlm16sXw0D6jAmekMADHLwFTDnMH8y9mahap5iEcJDq1j+tWS25olambfGiyykkEQLWxiWZ3z5bLrKiUGuD0k3q52EdIpRtn1QT19iNVbZqhCGJX5Gm7kzVFVSMH/O6oM47A6m2Orf/hL/EI6UScv7eOS47tVzew40CCwCHX8GJxBB15Of4bbuVlwSEEJ5WonSbSR+hG6X17lpzz5OIqStQbUQ6IrHTjcRuLHjY4wNNYtZCedI9VKenvVHEVERf4voomFm0LOdaHizORQFCbKEtg3iGv2rjVXWyShgC2fUFKfxv41UIL1W9/4KXmNpiTvgTaBz9N3gX4AqgnhMUYJXhZmqRqMaWBj5F3yrmr/7z/ad+8ZChAtwcIKEiLKnosU0+sTwcfya1odqMB7mklwCzpM9hzOXY1IFk9ojOh7fNt+eHg8UxMwh2O+d5xzyAZlcQAHmExsRp8XAsb9J1PiisAZ0ctVcKphrVHl0WIMe/GrgeWjwuvqKEElWXpHvZIzJvyFj7tINtvjJzefQjGs8XgpWNKbjhBmJLmrl/ABf1hFAA3fzyQyUde8A578mRAcffTEVXZjtz6JMg=
